export const siteConfig = {
  name: "Mark Lloyd Cuizon",
  title: "Full Stack Developer, Computer Engineer & AI Developer",
  primaryRole: "Full Stack Developer",
  secondaryRole: "AI Developer",
  description:
    "Building the future with code, circuits, and intelligence.",
  email: "cmark7781@gmail.com",
  phone: "+639260853647",
  location: "Minglanilla, Cebu City, Philippines",
  github: "https://github.com/Markishime",
  linkedin: "https://www.linkedin.com/in/mark-lloyd-cuizon-06a74820a/",
  education: {
    degree: "BS Computer Engineering",
    school: "Cebu Institute of Technology - University",
    years: "2021 – 2025",
  },
  roles: [
    "Full Stack Developer",
    "AI Developer",
    "Computer Engineer",
    "Embedded Systems",
  ],
  navLinks: [
    { label: "Home", href: "#home" },
    { label: "About", href: "#about" },
    { label: "Projects", href: "#projects" },
    { label: "Skills", href: "#skills" },
    { label: "Certifications", href: "#certifications" },
    { label: "Contact", href: "#contact" },
  ],
  projects: [
    {
      title: "Kinestra",
      description:
        "An AI-powered fitness platform built with React Native and Expo. It combines personalized Gemini-powered workout and nutrition coaching, conversational and voice guidance, computer-vision exercise analysis with pose estimation, progress tracking, and Firebase-backed authentication, storage, notifications, and cloud services.",
      tag: "Fitness + AI",
      lanes: ["ai", "web"],
      stack: ["React Native", "Expo", "TypeScript", "Firebase", "Gemini"],
      github: "https://github.com/Markishime/Kinestra",
      live: "https://kinestra.web.app/",
      gradient: "from-orange-500/25 to-rose-500/20",
      icon: "💪",
      image: "/media/kinestra.jpg",
      video: "/media/kinestra.mp4",
    },
    {
      title: "Smart EcoLock",
      description:
        "An IoT-based classroom door lock using ESP32-S3 with RFID access control, LDR-based auto-lighting, weight-sensor attendance tracking, and a real-time React.js admin dashboard with Firebase authentication and OTA updates.",
      tag: "Embedded System",
      lanes: ["embedded"],
      stack: ["ESP32", "RFID", "React", "Firebase"],
      github: "https://github.com/Markishime/smart-ecolock",
      live: null,
      gradient: "from-emerald-500/20 to-cyan-500/20",
      icon: "🔒",
      image: "/media/ecolock.jpg",
      video: "/media/ecolock.mp4",
    },
    {
      title: "AGS AI Assistant",
      description:
        "An AI-powered platform for Malaysian oil palm plantations that analyzes soil and leaf tissue data against MPOB 2022 standards. It identifies nutrient issues, recommends tiered interventions, forecasts yield and three-year ROI, supports sustainability assessments, and produces visual reports with PDF export.",
      tag: "AI/ML Integration",
      lanes: ["ai"],
      stack: ["Next.js", "Gemini", "Firebase", "LangChain", "Zod"],
      github: "https://github.com/Markishime/Ags-AI",
      live: "https://cropdrive.ai",
      gradient: "from-violet-500/20 to-fuchsia-500/20",
      icon: "🌿",
      image: "/media/cropdrive.jpg",
      video: null,
    },
    {
      title: "Team Builder",
      description:
        "A Streamlit application developed during a Connext internship to identify suitable job roles and calculate potential savings when hiring in the Philippines. It uses Ollama Llama 3.2 to process inputs, generate roles, and compare Philippine and US salaries.",
      tag: "AI/ML",
      lanes: ["ai", "web"],
      stack: ["Python", "Streamlit", "Ollama", "Llama 3.2"],
      github: "https://github.com/Markishime/team_builder",
      live: "https://mcteambuilder.streamlit.app/",
      gradient: "from-amber-500/20 to-orange-500/20",
      icon: "👥",
      image: "/media/teambuilder-reel.jpg",
      video: null,
    },
    {
      title: "LockMate",
      description:
        "An IoT keyless bicycle lock powered by ESP32 with web-based remote lock/unlock, real-time GPS tracking via NEO-8M, tampering alerts via Pushbullet, proximity theft alarm, and live weather updates.",
      tag: "Embedded System",
      lanes: ["embedded"],
      stack: ["ESP32", "GPS", "IoT"],
      github: "https://github.com/Markishime/LockMate",
      live: null,
      gradient: "from-blue-500/20 to-indigo-500/20",
      icon: "🚲",
      image: "/media/lockmate.jpg",
      video: "/media/lockmate.mp4",
    },
    {
      title: "CropDrive AI",
      description:
        "A bilingual precision-agriculture platform for Malaysian palm oil farmers. Gemini AI and OCR turn uploaded soil and leaf laboratory reports into recommendations benchmarked against MPOB standards, while Palmira provides follow-up guidance. Firebase stores accounts and report history, and Stripe supports subscription plans.",
      tag: "Web + AI/ML",
      lanes: ["ai", "web"],
      stack: ["Next.js", "Gemini", "OCR", "Firebase", "Stripe"],
      github: "https://github.com/Markishime/cropdrive",
      live: "https://cropdrive.ai",
      gradient: "from-green-500/20 to-teal-500/20",
      icon: "🌾",
      image: "/media/cropdrive.jpg",
      video: null,
    },
    {
      title: "Simplabots",
      description:
        "An AI-powered business automation platform featuring agents for website chat and lead capture, image generation, call handling, email assistance, ad copy, domain discovery, and recruitment workflows. The platform combines LLMs, LangChain automation, APIs, and cloud services in a scalable SaaS architecture.",
      tag: "Web + AI/ML",
      lanes: ["ai", "web"],
      stack: ["AI Agents", "LLMs", "LangChain", "APIs", "SaaS"],
      github: null,
      live: "https://simplabots.com/",
      gradient: "from-rose-500/20 to-pink-500/20",
      icon: "🤖",
      image: "/media/simplabots.jpg",
      video: null,
    },
    {
      title: "Masbate Today",
      description:
        "A web development project for Masbate. The supplied CV lists the project without additional implementation or feature details.",
      tag: "Web Development",
      lanes: ["web"],
      stack: ["Web Development"],
      github: "https://github.com/Markishime/MasbateToday",
      live: "https://masbatetoday.web.app/",
      gradient: "from-sky-500/20 to-blue-500/20",
      icon: "🏝️",
      image: "/media/masbate.jpg",
      video: null,
    },
    {
      title: "Soda+",
      description:
        "An immersive single-page marketing landing page for a fictional premium zero-sugar sparkling beverage brand. Features interactive 3D product models via model-viewer, GSAP-powered scroll animations, parallax motion, a 3D review card carousel, flavor switching with full-body choreography, glassmorphism UI, and a rich visual narrative spanning ingredients, taste, sustainability, nutrition, and customer reviews.",
      tag: "Web Development",
      lanes: ["web"],
      stack: ["HTML5", "CSS3", "JavaScript", "GSAP", "3D Web"],
      github: "https://github.com/Markishime/Soda",
      live: "https://soda-plus.vercel.app/",
      gradient: "from-pink-500/25 to-rose-500/20",
      icon: "🥤",
      image: "/media/soda-plus.jpg",
      video: null,
    },
  ],
  skills: {
    languages: [
      "Python",
      "TypeScript",
      "JavaScript (ES6+)",
      "Dart",
      "HTML5",
      "CSS3",
    ],
    frontend: [
      "React.js",
      "Next.js",
      "React Native",
      "Expo",
      "Flutter",
      "Tailwind CSS",
      "Bootstrap",
      "Streamlit",
    ],
    backend: [
      "Node.js",
      "Express.js",
      "FastAPI",
      "Flask",
      "REST APIs",
      "Serverless Functions",
    ],
    artificialIntelligence: [
      "Generative AI",
      "AI Agents",
      "Large Language Models (LLMs)",
      "Google Gemini AI",
      "LangChain",
      "Retrieval-Augmented Generation (RAG)",
      "Prompt Engineering",
      "TensorFlow",
      "Computer Vision",
      "OCR",
      "Conversational AI",
      "AI Workflow Automation",
    ],
    mobile: [
      "React Native",
      "Expo",
      "Flutter",
      "Cross-Platform Mobile Development",
    ],
    databasesCloud: [
      "Firebase (Authentication, Firestore, Realtime Database, Cloud Functions)",
      "Supabase",
      "PostgreSQL",
      "Vercel",
    ],
    embedded: [
      "ESP32",
      "ESP32-S3",
      "Arduino",
      "RFID",
      "GPS Modules",
      "Sensors",
      "OTA Updates",
      "Embedded Systems",
    ],
    developmentTools: [
      "Git",
      "GitHub",
      "Cursor",
      "Windsurf",
      "Visual Studio Code",
      "Claude Code",
      "Grok Code",
      "OpenAI Codex",
      "Android Studio",
      "Arduino IDE",
      "FlutterFlow",
    ],
    softwareEngineering: [
      "Full Stack Development",
      "System Architecture",
      "API Integration",
      "Database Design",
      "Authentication & Authorization",
      "Responsive UI/UX",
      "Performance Optimization",
      "Agile Development",
    ],
    professional: [
      "Problem Solving",
      "Analytical Thinking",
      "Critical Thinking",
      "AI Solution Design",
      "Software Architecture",
      "Team Collaboration",
      "Leadership",
      "Communication",
      "Project Management",
      "Adaptability",
      "Continuous Learning",
      "Attention to Detail",
      "Time Management",
    ],
  },
  hackathons: [
    { name: "CopernicusLAC Panamá", role: "Hackathon Participant" },
    { name: "Connext AI Solutions", role: "Hackathon Participant" },
    { name: "Starknet Winter", role: "Hackathon Participant" },
  ],
  certifications: [
    "Data Engineering Fundamentals: From Raw Data to Insights Certificate",
    "Globe Business Breakthrough: AI-driven Future of Manufacturing and Logistics Operations Certificate",
    "Mastering Digital Marketing in an AI world Certificate",
    "Design for Innovation: How to Build for Change Certificate",
    "The Power of Tiny: Enabling the Future with Microcontrollers Certificate",
    "AI powered Marketing: Unlocking the future of Smarter Strategies Certificate",
    "Mastering Digital Success: From Web Development to Virtual Innovation Certificate",
    "Data Analytics for Smarter Decision-Making Certificate",
    "Strengthen Business and Education using AI Certificate",
    "Analysis of Algorithms Certificate",
    "Cloud Sync: Firebase 101 Certificate",
  ],
} as const;
