export const siteConfig = {
  name: "Mark Lloyd Cuizon",
  title: "Computer Engineer & AI Developer",
  description:
    "Building the future with code, circuits, and intelligence.",
  email: "cmark7781@gmail.com",
  phone: "+639260853647",
  location: "Minglanilla, Cebu City, Philippines",
  github: "https://github.com/Markishime",
  linkedin: "https://www.linkedin.com/in/mark-lloyd-cuizon-06a74820a/",
  education: {
    degree: "BS Computer Engineering",
    school: "Cebu Institute of Technology - University",
    years: "2021 – 2025",
  },
  roles: [
    "Computer Engineer",
    "Full-Stack Developer",
    "AI Developer",
    "IoT Engineer",
    "ML Enthusiast",
  ],
  navLinks: [
    { label: "Home", href: "#home" },
    { label: "About", href: "#about" },
    { label: "Projects", href: "#projects" },
    { label: "Skills", href: "#skills" },
    { label: "Certifications", href: "#certifications" },
    { label: "Contact", href: "#contact" },
  ],
  projects: [
    {
      title: "Orbit AI",
      description:
        "A personal life OS that brings everyday planning into one hub: tasks, habits, bills, meds, notes, goals, projects, focus work, and an AI planning assistant. Built as a single HTML/JavaScript PWA with Capacitor packaging for Google Play and the App Store. Firebase Auth, Cloud Firestore sync, and Cloud Storage power accounts and data; demo mode with localStorage works when Firebase is not configured. Offline-ready via Firestore persistence plus a localStorage mirror. Architecture: Orbit AI.dc.html UI over a shared OrbitBackend layer for auth, database, and storage.",
      tag: "Life OS + AI",
      github: "https://github.com/Markishime/Orbit-AI",
      live: null,
      gradient: "from-indigo-500/25 to-cyan-500/20",
      icon: "🛰️",
    },
    {
      title: "Kinestra",
      description:
        "All-in-one fitness app: Train Smarter. Move Better. Live Stronger. Replaces separate workout, nutrition, GPS, progress, and social apps with one product sharing the same user data. Deep onboarding (body stats, goals, experience, equipment, schedule, injuries, diet, sleep, stress) feeds a 52-week periodized engine with progressive overload, equipment-aware swaps, rest timers, and XP. Kine, a Gemini-powered AI coach, designs programs, answers with your history, and speaks hands-free. Nutrition covers macros, water, and AI meal photo scanning. Live GPS for runs, rides, and walks with Kalman-filtered tracking. Progress, readiness, streaks, and social (feed, DMs, stories, workout sharing). React + TanStack + Firebase web app; Android via Capacitor.",
      tag: "Fitness + AI",
      github: "https://github.com/Markishime/Kinestra",
      live: null,
      gradient: "from-orange-500/25 to-rose-500/20",
      icon: "💪",
    },
    {
      title: "Smart EcoLock",
      description:
        "An IoT-based classroom door lock using ESP32-S3 with RFID access control, LDR-based auto-lighting, weight-sensor attendance tracking, and a real-time React.js admin dashboard with Firebase authentication and OTA updates.",
      tag: "Embedded System",
      github: "https://github.com/Markishime/smart-ecolock",
      live: null,
      gradient: "from-emerald-500/20 to-cyan-500/20",
      icon: "🔒",
    },
    {
      title: "AGS AI Assistant",
      description:
        "An AI-powered agronomic assistant for Malaysian oil palm plantations — embedded as the core AI engine of CropDrive AI. Processes soil and leaf data against MPOB 2022 standards for nutrient analysis, fertilizer recommendations, and 3-year ROI projections.",
      tag: "AI/ML Integration",
      github: "https://github.com/Markishime/Ags-AI",
      live: "https://cropdrive.ai",
      gradient: "from-violet-500/20 to-fuchsia-500/20",
      icon: "🌿",
    },
    {
      title: "Team Builder",
      description:
        "An AI-powered staffing cost calculator built with Streamlit and Google Gemini AI for Connext Global Solutions — helping prospective clients visualize offshore team savings in the Philippines.",
      tag: "AI/ML",
      github: "https://github.com/Markishime/team_builder",
      live: "https://mcteambuilder.streamlit.app/",
      gradient: "from-amber-500/20 to-orange-500/20",
      icon: "👥",
    },
    {
      title: "LockMate",
      description:
        "An IoT keyless bicycle lock powered by ESP32 with web-based remote lock/unlock, real-time GPS tracking via NEO-8M, tampering alerts via Pushbullet, proximity theft alarm, and live weather updates.",
      tag: "Embedded System",
      github: "https://github.com/Markishime/LockMate",
      live: null,
      gradient: "from-blue-500/20 to-indigo-500/20",
      icon: "🚲",
    },
    {
      title: "CropDrive AI",
      description:
        "An AI-powered precision agriculture platform. Farmers upload soil or leaf lab reports; Gemini AI + OCR extracts and analyzes data against MPOB standards, delivering recommendations via Palmira — a bilingual AI chat assistant.",
      tag: "Web + AI/ML",
      github: "https://github.com/Markishime/cropdrive",
      live: "https://cropdrive.ai",
      gradient: "from-green-500/20 to-teal-500/20",
      icon: "🌾",
    },
    {
      title: "Simplabots",
      description:
        "An AI-powered business automation platform with custom agents for chatbot support, email automation, call handling, image generation, ad copywriting, domain naming, and recruitment workflows.",
      tag: "Web + AI/ML",
      github: null,
      live: "https://simplabots.com/",
      gradient: "from-rose-500/20 to-pink-500/20",
      icon: "🤖",
    },
    {
      title: "MasbateToday",
      description:
        "A full-featured tourism and news platform for Masbate Province, Philippines. Includes local news, travel destinations with booking (GCash, Stripe, cash), a Gemini AI chatbot, real-time officials directory, weather widget, video/photo gallery, and a Firebase-powered admin dashboard.",
      tag: "Web + AI/ML",
      github: "https://github.com/Markishime/MasbateToday",
      live: "https://masbatetoday.vercel.app/",
      gradient: "from-sky-500/20 to-blue-500/20",
      icon: "🏝️",
    },
  ],
  skills: {
    languages: [
      { name: "Python", level: 92 },
      { name: "TypeScript", level: 88 },
      { name: "JavaScript", level: 90 },
      { name: "Dart", level: 78 },
      { name: "HTML/CSS", level: 95 },
      { name: "C/C++", level: 70 },
    ],
    frameworks: [
      "Next.js",
      "React.js",
      "Node.js",
      "Flutter",
      "Flask",
      "Streamlit",
      "LangChain",
      "TensorFlow",
    ],
    tools: [
      "Firebase",
      "Supabase",
      "PostgreSQL",
      "Vercel",
      "FlutterFlow",
      "Flowise",
      "Git",
      "Docker",
    ],
    hardware: [
      "ESP32",
      "ESP32-S3",
      "Arduino Uno",
      "RFID Modules",
      "NEO-8M GPS",
      "Relay Modules",
      "Vibration Sensors",
      "LDR Sensors",
    ],
  },
  hackathons: [
    { name: "CopernicusLAC Panamá", role: "Hackathon Participant" },
    { name: "Connext AI Solutions", role: "Hackathon Participant" },
    { name: "Starknet Winter", role: "Hackathon Participant" },
  ],
  certifications: [
    "Data Engineering Fundamentals: From Raw Data to Insights",
    "Globe Business Breakthrough: AI-driven Future of Manufacturing & Logistics",
    "Mastering Digital Marketing in an AI World",
    "Design for Innovation: How to Build for Change",
    "The Power of Tiny: Enabling the Future with Microcontrollers",
    "AI Powered Marketing: Unlocking the Future of Smarter Strategies",
    "Mastering Digital Success: From Web Development to Virtual Innovation",
    "Data Analytics for Smarter Decision-Making",
    "Strengthen Business and Education using AI",
    "Analysis of Algorithms",
    "Cloud Sync: Firebase 101",
  ],
} as const;
